using NUnit.Framework;
using NUnit.Framework.Interfaces;
using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public enum RunPhase
{
    Draft,
    RoomActive,
    RoomTransition,
    RunComplete,
    RunFailure
}

public class RunManager : MonoBehaviour
{
    public static RunManager Instance { get; private set; }
    // Room Pool

    private CurrentRun currentRun;

    private Player activePlayer;
    private RoomManager activeRoom;

    private RunPhase phase;

    [SerializeField] private Player playerPrefab;

    private void Awake()
    {
        if (Instance == null)
            Instance = this;
        else
            Destroy(gameObject);
    }

    // Start run after map generated by draft
    public void BeginRun(RunMap map, CurrentRun runState, RunLoadout loadout)
    {
        currentRun = runState;
        
        // Initialize Player

    }

    private void EnterNode(MapNode node, Doorway entryPoint)
    {
        phase = RunPhase.RoomActive;
        currentRun.currentMap.currentNode = node;

        // Get active room from pool
        activeRoom.Initialize(node.room, currentRun);

        activeRoom.OnCleared += HandleRoomCleared;
        activeRoom.OnFailure += HandleRoomFailed;

        Vector2 spawnPos = entryPoint != null 
            ? activeRoom.GetEntryPointFor(entryPoint) 
            : activeRoom.defaultEntryPoint;

        //


        activeRoom.Activate();
    }

    private void HandleRoomCleared(RoomManager room)
    {
        room.OnCleared -= HandleRoomCleared;
        room.OnFailure -= HandleRoomFailed;

        phase = RunPhase.RoomTransition;
    }

    private void HandleRoomFailed(RoomManager room)
    {
        phase = RunPhase.RunFailure;

    }

    // Called by doorways when walked through to progress
    public void TransitionTo(MapNode nextNode)
    {
        // Disable current room
        activeRoom = null;
        EnterNode(nextNode, null);
    }

}

[Serializable]
public class CurrentRun
{
    // Run
    public int RunSeed;

    public int chapterIndex;
    public RunMap currentMap;
    // Draft things

    public float runTimer;

    // Player    
    public PlayerData player;

    // Rooms
    public float HeatLevel;

    // Stats
    public int EnemiesKilled;
    public float RunDuration;
    public int DamageTaken;

}


// Packed and saved after each room. Used to restore player when loading back into run.
[Serializable]
public class PlayerData
{
    // Structure info

    public int activeSegmentIndex;

    // Momentum info
    public float CurrentMomentum;

    // Upgrade info
    public List<string> UpgradesGained = new();
}