using DG.Tweening;
using NUnit.Framework;
using NUnit.Framework.Interfaces;
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using static UnityEngine.Rendering.STP;

public enum RunState
{
    Draft,
    RoomActive,
    RoomTransition,
    RunComplete,
    RunFailure
}

public class RunManager : MonoBehaviour
{
    public static RunManager Instance { get; private set; }

    public GameDatabase db;

    [SerializeField] private Transform roomContainer;
    [SerializeField] private Transform enemyContainer;
    [SerializeField] private Transform playerContainer;

    [SerializeField] private float fadeTime;
    [SerializeField] private CanvasGroup fadeOverlay;

    public RoomPoolService roomService; // Pools rooms, holds useful values etc
    public EnemyService enemyService; // Pools enemies, allows for spawning and handling etc
    public RunState state { get; private set; }

    private CurrentRun currentRun;

    private Player activePlayer;
    private RoomManager activeRoom;

    [SerializeField] private Player playerPrefab;

    private void Awake()
    {
        if (Instance == null)
            Instance = this;
        else
            Destroy(gameObject);

        roomService = new RoomPoolService(db.rooms, roomContainer);
        enemyService = new EnemyService(db.enemies, enemyContainer);
    }

    private void Start()
    {
        BeginRun();
    }

    private void Update()
    {
        UpdateRunTick();
    }

    //// Start run after map generated by draft
    //public void BeginRun(RunMap map, CurrentRun runState, RunLoadout loadout)
    //{
    //    currentRun = runState;
        
    //    activePlayer = Instantiate(playerPrefab, Vector2.zero, Quaternion.identity);
    //    activePlayer.SetupNew(loadout);

    //    // Initialize Player
    //    EnterNode(map.startNode, null);
    //}

    public void BeginRun()
    {
        RunConfig config = RunDataCarrier.ConsumeData();

        currentRun = new(config.seed, config.map);
        roomService.BuildPool(config.map);

        activePlayer = Instantiate(playerPrefab, playerContainer);
        activePlayer.SetupNew(config.loadout);

        EnterNode(config.map.startNode, null);
    }

    public void LoadToRun(CurrentRun run)
    {
        currentRun = run;

        activePlayer = Instantiate(playerPrefab, Vector2.zero, Quaternion.identity);
        activePlayer.SetupFromSave(null); // REMOVE NULL

        //EnterNode()
    }

    #region Room Transitions

    private void EnterNode(MapNode node, Direction? arrivingFrom)
    {
        state = RunState.RoomActive;
        currentRun.map.currentNode = node;

        // Get active room from pool
        if (roomService == null)
        {
            Debug.LogError("[RunManager] No RoomService existing :(");
            return;
        }
        
        activeRoom = roomService.GetRoom(node);
        activeRoom.Initialize(node, currentRun);

        activeRoom.OnCleared += HandleRoomCleared;
        activeRoom.OnFailure += HandleRoomFailed;

        Vector2 spawnPos = arrivingFrom.HasValue
            ? activeRoom.GetEntryPointFor(arrivingFrom.Value.Opposite())
            : activeRoom.defaultEntryPoint;

        GameEvents.PlayerTransitionTeleport(spawnPos);
        activePlayer.transform.position = spawnPos;

        //DoTransitionFade(false); // Unhide Screen

        activeRoom.Activate();
    }

    private void HandleRoomCleared(RoomManager room)
    {
        room.OnCleared -= HandleRoomCleared;
        room.OnFailure -= HandleRoomFailed;

        currentRun.map.currentNode.cleared = true;

        state = RunState.RoomTransition;
    }

    private void HandleRoomFailed(RoomManager room)
    {
        state = RunState.RunFailure;

    }

    // Called by doorways when walked through to progress
    public void TransitionTo(MapNode nextNode, Direction exitDirection)
    {
        // Disable current room
        //DoTransitionFade(true); // Do Visual hiding

        //StartCoroutine(TransitionRoutine(nextNode, exitDirection));

        roomService.ReturnToPool(activeRoom);
        activeRoom = null;
        EnterNode(nextNode, null); // Change null to exit direction
    }

    public IEnumerator TransitionRoutine(MapNode nextNode, Direction dir)
    {
        DoTransitionFade(true);

        yield return new WaitForSeconds(fadeTime);
        EnterNode(nextNode, null); // Change null to exit direction

        DoTransitionFade(false);
    }

    private void DoTransitionFade(bool enable)
    {
        if (fadeOverlay == null) return;

        float fadeValue = enable ? 1f : 0f;

        fadeOverlay?.DOKill();
        fadeOverlay.DOFade(fadeValue, fadeTime).SetUpdate(true);
    }

    #endregion

    private void UpdateRunTick()
    {
        if (currentRun == null) return;
        if (TimescaleManager.IsPaused) return;

        switch (state)
        {
            case RunState.RoomActive:
                currentRun.Tick(Time.deltaTime);
                break;

            case RunState.RoomTransition:
                currentRun.Tick(Time.deltaTime / 2);
                break;

            case RunState.Draft:
            case RunState.RunComplete:
            case RunState.RunFailure:
                break;

        }
    }

    #region Save System

    #endregion
}

[Serializable]
public class CurrentRun
{
    // Run
    public int RunSeed;

    // Map
    public int chapterIndex;
    public RunMap map;
    public Doorway lastDoorway; // used to re-load spawn pos
    // Draft things

    public float runDurationTimer;
    public float playerHeatTimer;

    // Rooms
    public float HeatLevel;

    // Stats
    public int EnemiesKilled;
    public int DamageTaken;

    public CurrentRun(int seed, RunMap map)
    {
        RunSeed = seed;
        this.map = map;

        runDurationTimer = 0f;
        playerHeatTimer = 120f; // Change to variable start time??

        EnemiesKilled = 0;
        DamageTaken = 0;
    }

    public void Tick(float dt)
    {
        runDurationTimer += dt;
        playerHeatTimer -= dt;
        if (playerHeatTimer <= 0)
        {
            // Fire Event   
        }
    }

    public void HeatReset()
    {

    }

}